import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const STARTER_TEMPLATES = [
  // ─── BUSINESS ───────────────────────────────────────────────────────────────
  {
    name: "Analise SWOT",
    description: "Forcas, Fraquezas, Oportunidades e Ameacas",
    category: "business",
    node_count: 13,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Analise SWOT", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -120 }, data: { label: "Forcas", color: "#22C55E", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 120 }, data: { label: "Fraquezas", color: "#EF4444", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -120 }, data: { label: "Oportunidades", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: 120 }, data: { label: "Ameacas", color: "#F59E0B", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 560, y: -160 }, data: { label: "Ponto forte 1", color: "#22C55E", level: 2, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: 560, y: -80 }, data: { label: "Ponto forte 2", color: "#22C55E", level: 2, side: "right" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: 80 }, data: { label: "Ponto fraco 1", color: "#EF4444", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: 160 }, data: { label: "Ponto fraco 2", color: "#EF4444", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "Oportunidade 1", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n11", type: "mindmap", position: { x: -560, y: -80 }, data: { label: "Oportunidade 2", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: 80 }, data: { label: "Ameaca 1", color: "#F59E0B", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: 160 }, data: { label: "Ameaca 2", color: "#F59E0B", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e2-6", source: "n2", target: "n6", type: "mindmap" },
        { id: "e2-7", source: "n2", target: "n7", type: "mindmap" },
        { id: "e3-8", source: "n3", target: "n8", type: "mindmap" },
        { id: "e3-9", source: "n3", target: "n9", type: "mindmap" },
        { id: "e4-10", source: "n4", target: "n10", type: "mindmap" },
        { id: "e4-11", source: "n4", target: "n11", type: "mindmap" },
        { id: "e5-12", source: "n5", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
      ],
    },
  },
  {
    name: "Plano de Projeto",
    description: "Estrutura basica para planejamento de projetos",
    category: "business",
    node_count: 13,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Plano de Projeto", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -160 }, data: { label: "Escopo", color: "#C4A882", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 0 }, data: { label: "Cronograma", color: "#7C9E8F", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -120 }, data: { label: "Recursos", color: "#8B9CC4", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: 80 }, data: { label: "Riscos", color: "#C48BB4", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 560, y: -200 }, data: { label: "Objetivos", color: "#C4A882", level: 2, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: 560, y: -120 }, data: { label: "Entregas", color: "#C4A882", level: 2, side: "right" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -40 }, data: { label: "Marcos", color: "#7C9E8F", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: 40 }, data: { label: "Prazos", color: "#7C9E8F", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "Equipe", color: "#8B9CC4", level: 2, side: "left" } },
        { id: "n11", type: "mindmap", position: { x: -560, y: -80 }, data: { label: "Orcamento", color: "#8B9CC4", level: 2, side: "left" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: 40 }, data: { label: "Mitigacao", color: "#C48BB4", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: 120 }, data: { label: "Contingencia", color: "#C48BB4", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e2-6", source: "n2", target: "n6", type: "mindmap" },
        { id: "e2-7", source: "n2", target: "n7", type: "mindmap" },
        { id: "e3-8", source: "n3", target: "n8", type: "mindmap" },
        { id: "e3-9", source: "n3", target: "n9", type: "mindmap" },
        { id: "e4-10", source: "n4", target: "n10", type: "mindmap" },
        { id: "e4-11", source: "n4", target: "n11", type: "mindmap" },
        { id: "e5-12", source: "n5", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
      ],
    },
  },
  {
    name: "Business Model Canvas",
    description: "Os 9 blocos do modelo de negocios",
    category: "business",
    node_count: 10,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Business Model Canvas", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -200 }, data: { label: "Proposta de Valor", color: "#22C55E", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: -80 }, data: { label: "Segmentos de Clientes", color: "#C4A882", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: 280, y: 40 }, data: { label: "Canais", color: "#3B82F6", level: 1, side: "right" } },
        { id: "n5", type: "mindmap", position: { x: 280, y: 160 }, data: { label: "Relacionamento", color: "#8B9CC4", level: 1, side: "right" } },
        { id: "n6", type: "mindmap", position: { x: -280, y: -200 }, data: { label: "Atividades-Chave", color: "#C48BB4", level: 1, side: "left" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: -80 }, data: { label: "Recursos-Chave", color: "#7C9E8F", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: -280, y: 40 }, data: { label: "Parcerias-Chave", color: "#F59E0B", level: 1, side: "left" } },
        { id: "n9", type: "mindmap", position: { x: -280, y: 160 }, data: { label: "Estrutura de Custos", color: "#EF4444", level: 1, side: "left" } },
        { id: "n10", type: "mindmap", position: { x: 0, y: 280 }, data: { label: "Fontes de Receita", color: "#22C55E", level: 1, side: "right" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "right" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "right" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "left" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e1-8", source: "n1", target: "n8", type: "mindmap", sourceHandle: "left" },
        { id: "e1-9", source: "n1", target: "n9", type: "mindmap", sourceHandle: "left" },
        { id: "e1-10", source: "n1", target: "n10", type: "mindmap", sourceHandle: "right" },
      ],
    },
  },
  {
    name: "Analise de Concorrencia",
    description: "Mapeamento competitivo e diferenciais",
    category: "business",
    node_count: 13,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Analise Competitiva", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -120 }, data: { label: "Concorrentes Diretos", color: "#EF4444", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 120 }, data: { label: "Concorrentes Indiretos", color: "#F59E0B", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -120 }, data: { label: "Nossos Diferenciais", color: "#22C55E", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: 120 }, data: { label: "Oportunidades de Mercado", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 560, y: -180 }, data: { label: "Preco e Posicionamento", color: "#EF4444", level: 2, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: 560, y: -100 }, data: { label: "Pontos Fortes Deles", color: "#EF4444", level: 2, side: "right" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -20 }, data: { label: "Pontos Fracos Deles", color: "#EF4444", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: 80 }, data: { label: "Substitutos", color: "#F59E0B", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: 160 }, data: { label: "Novos Entrantes", color: "#F59E0B", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "Tecnologia", color: "#22C55E", level: 2, side: "left" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: -80 }, data: { label: "Atendimento", color: "#22C55E", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: 120 }, data: { label: "Nichos Inexplorados", color: "#3B82F6", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e2-6", source: "n2", target: "n6", type: "mindmap" },
        { id: "e2-7", source: "n2", target: "n7", type: "mindmap" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e3-9", source: "n3", target: "n9", type: "mindmap" },
        { id: "e3-10", source: "n3", target: "n10", type: "mindmap" },
        { id: "e4-11", source: "n4", target: "n11", type: "mindmap" },
        { id: "e4-12", source: "n4", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
      ],
    },
  },
  {
    name: "Plano de Marketing",
    description: "Estrategia de marketing com os 4Ps e acoes",
    category: "business",
    node_count: 15,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Plano de Marketing", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -200 }, data: { label: "Produto", color: "#22C55E", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: -60 }, data: { label: "Preco", color: "#C4A882", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -200 }, data: { label: "Praca (Distribuicao)", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: -60 }, data: { label: "Promocao", color: "#C48BB4", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 280, y: 120 }, data: { label: "Publico-Alvo", color: "#F59E0B", level: 1, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: 120 }, data: { label: "Metricas e KPIs", color: "#7C9E8F", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -240 }, data: { label: "Beneficios", color: "#22C55E", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -160 }, data: { label: "Diferenciais", color: "#22C55E", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: -80 }, data: { label: "Estrategia de Preco", color: "#C4A882", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: 80 }, data: { label: "Persona", color: "#F59E0B", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: 560, y: 160 }, data: { label: "Dor Principal", color: "#F59E0B", level: 2, side: "right" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: -240 }, data: { label: "Canais Online", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n14", type: "mindmap", position: { x: -560, y: -100 }, data: { label: "Redes Sociais", color: "#C48BB4", level: 2, side: "left" } },
        { id: "n15", type: "mindmap", position: { x: -560, y: 80 }, data: { label: "CAC / LTV / ROI", color: "#7C9E8F", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "right" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e3-10", source: "n3", target: "n10", type: "mindmap" },
        { id: "e6-11", source: "n6", target: "n11", type: "mindmap" },
        { id: "e6-12", source: "n6", target: "n12", type: "mindmap" },
        { id: "e4-13", source: "n4", target: "n13", type: "mindmap" },
        { id: "e5-14", source: "n5", target: "n14", type: "mindmap" },
        { id: "e7-15", source: "n7", target: "n15", type: "mindmap" },
      ],
    },
  },

  // ─── ACADEMIC ───────────────────────────────────────────────────────────────
  {
    name: "Resumo de Livro",
    description: "Estrutura para sintetizar ideias-chave de um livro",
    category: "academic",
    node_count: 13,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Titulo do Livro", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -160 }, data: { label: "Tese Central", color: "#22C55E", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 0 }, data: { label: "Capitulos-Chave", color: "#C4A882", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -160 }, data: { label: "Contexto do Autor", color: "#8B9CC4", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: 0 }, data: { label: "Aplicacoes Praticas", color: "#7C9E8F", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 280, y: 160 }, data: { label: "Criticas e Reflexoes", color: "#C48BB4", level: 1, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: 160 }, data: { label: "Citacoes Importantes", color: "#F59E0B", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -200 }, data: { label: "Argumento Principal", color: "#22C55E", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -120 }, data: { label: "Evidencias", color: "#22C55E", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: -40 }, data: { label: "Capitulo 1", color: "#C4A882", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: 40 }, data: { label: "Capitulo 2", color: "#C4A882", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: -40 }, data: { label: "No trabalho", color: "#7C9E8F", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: 40 }, data: { label: "Na vida pessoal", color: "#7C9E8F", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "right" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e3-10", source: "n3", target: "n10", type: "mindmap" },
        { id: "e3-11", source: "n3", target: "n11", type: "mindmap" },
        { id: "e5-12", source: "n5", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
      ],
    },
  },
  {
    name: "Estudo de Caso",
    description: "Framework para analise de estudos de caso",
    category: "academic",
    node_count: 13,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Estudo de Caso", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -160 }, data: { label: "Contexto", color: "#C4A882", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 0 }, data: { label: "Problema Central", color: "#EF4444", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: 280, y: 160 }, data: { label: "Solucao Proposta", color: "#22C55E", level: 1, side: "right" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: -160 }, data: { label: "Dados e Evidencias", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: -280, y: 0 }, data: { label: "Analise Critica", color: "#C48BB4", level: 1, side: "left" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: 160 }, data: { label: "Conclusoes", color: "#7C9E8F", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -200 }, data: { label: "Cenario de Mercado", color: "#C4A882", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -120 }, data: { label: "Stakeholders", color: "#C4A882", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: 0 }, data: { label: "Causa Raiz", color: "#EF4444", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: 120 }, data: { label: "Implementacao", color: "#22C55E", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "Quantitativos", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: 0 }, data: { label: "Pontos Fortes/Fracos", color: "#C48BB4", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "right" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "left" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e3-10", source: "n3", target: "n10", type: "mindmap" },
        { id: "e4-11", source: "n4", target: "n11", type: "mindmap" },
        { id: "e5-12", source: "n5", target: "n12", type: "mindmap" },
        { id: "e6-13", source: "n6", target: "n13", type: "mindmap" },
      ],
    },
  },
  {
    name: "Fichamento Academico",
    description: "Estrutura para fichamento de artigos e textos",
    category: "academic",
    node_count: 11,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Fichamento", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -120 }, data: { label: "Referencia Bibliografica", color: "#C4A882", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 40 }, data: { label: "Ideias Principais", color: "#22C55E", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -120 }, data: { label: "Metodologia", color: "#8B9CC4", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: 40 }, data: { label: "Resultados", color: "#7C9E8F", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 280, y: 160 }, data: { label: "Citacoes Diretas", color: "#F59E0B", level: 1, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: 160 }, data: { label: "Comentarios Pessoais", color: "#C48BB4", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -160 }, data: { label: "Autor / Ano", color: "#C4A882", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -80 }, data: { label: "Titulo / Publicacao", color: "#C4A882", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: -560, y: -120 }, data: { label: "Abordagem", color: "#8B9CC4", level: 2, side: "left" } },
        { id: "n11", type: "mindmap", position: { x: -560, y: 40 }, data: { label: "Conclusoes do Autor", color: "#7C9E8F", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "right" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e4-10", source: "n4", target: "n10", type: "mindmap" },
        { id: "e5-11", source: "n5", target: "n11", type: "mindmap" },
      ],
    },
  },
  {
    name: "Estrutura de TCC",
    description: "Organizacao completa de trabalho de conclusao de curso",
    category: "academic",
    node_count: 15,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "TCC", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -200 }, data: { label: "Introducao", color: "#C4A882", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: -60 }, data: { label: "Referencial Teorico", color: "#8B9CC4", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: 280, y: 80 }, data: { label: "Resultados", color: "#22C55E", level: 1, side: "right" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: -200 }, data: { label: "Metodologia", color: "#7C9E8F", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: -280, y: -60 }, data: { label: "Discussao", color: "#C48BB4", level: 1, side: "left" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: 80 }, data: { label: "Conclusao", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: 280, y: 200 }, data: { label: "Referencias", color: "#F59E0B", level: 1, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -240 }, data: { label: "Problema de Pesquisa", color: "#C4A882", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: -160 }, data: { label: "Objetivos", color: "#C4A882", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: -80 }, data: { label: "Justificativa", color: "#C4A882", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: -240 }, data: { label: "Tipo de Pesquisa", color: "#7C9E8F", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "Coleta de Dados", color: "#7C9E8F", level: 2, side: "left" } },
        { id: "n14", type: "mindmap", position: { x: 560, y: 40 }, data: { label: "Analise dos Dados", color: "#22C55E", level: 2, side: "right" } },
        { id: "n15", type: "mindmap", position: { x: 560, y: 120 }, data: { label: "Graficos e Tabelas", color: "#22C55E", level: 2, side: "right" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "right" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "left" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e1-8", source: "n1", target: "n8", type: "mindmap", sourceHandle: "right" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e2-10", source: "n2", target: "n10", type: "mindmap" },
        { id: "e2-11", source: "n2", target: "n11", type: "mindmap" },
        { id: "e5-12", source: "n5", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
        { id: "e4-14", source: "n4", target: "n14", type: "mindmap" },
        { id: "e4-15", source: "n4", target: "n15", type: "mindmap" },
      ],
    },
  },

  // ─── CREATIVE ───────────────────────────────────────────────────────────────
  {
    name: "Brainstorm",
    description: "Estrutura para sessao de brainstorming",
    category: "creative",
    node_count: 11,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Tema Central", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -120 }, data: { label: "Ideia 1", color: "#C4A882", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 40 }, data: { label: "Ideia 2", color: "#7C9E8F", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -120 }, data: { label: "Ideia 3", color: "#8B9CC4", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: 40 }, data: { label: "Ideia 4", color: "#C48BB4", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 280, y: 160 }, data: { label: "Ideia 5", color: "#F59E0B", level: 1, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: 160 }, data: { label: "Ideia 6", color: "#22C55E", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -160 }, data: { label: "Detalhe 1.1", color: "#C4A882", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -80 }, data: { label: "Detalhe 1.2", color: "#C4A882", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "Detalhe 3.1", color: "#8B9CC4", level: 2, side: "left" } },
        { id: "n11", type: "mindmap", position: { x: -560, y: -80 }, data: { label: "Detalhe 3.2", color: "#8B9CC4", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "right" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e4-10", source: "n4", target: "n10", type: "mindmap" },
        { id: "e4-11", source: "n4", target: "n11", type: "mindmap" },
      ],
    },
  },
  {
    name: "Mapa de Empatia",
    description: "Entenda seu usuario: pensa, sente, faz, diz",
    category: "creative",
    node_count: 13,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Mapa de Empatia", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -120 }, data: { label: "O que Pensa e Sente", color: "#C48BB4", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 120 }, data: { label: "O que Fala e Faz", color: "#C4A882", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: -280, y: -120 }, data: { label: "O que Ve", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: 120 }, data: { label: "O que Ouve", color: "#8B9CC4", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: 0, y: -240 }, data: { label: "Dores", color: "#EF4444", level: 1, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: 0, y: 240 }, data: { label: "Ganhos", color: "#22C55E", level: 1, side: "right" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -160 }, data: { label: "Preocupacoes", color: "#C48BB4", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -80 }, data: { label: "Aspiracoes", color: "#C48BB4", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: 80 }, data: { label: "Comportamento", color: "#C4A882", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: 160 }, data: { label: "Atitudes", color: "#C4A882", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: -120 }, data: { label: "Ambiente", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: 120 }, data: { label: "Influencias", color: "#8B9CC4", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "left" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "right" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "right" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e3-10", source: "n3", target: "n10", type: "mindmap" },
        { id: "e3-11", source: "n3", target: "n11", type: "mindmap" },
        { id: "e4-12", source: "n4", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
      ],
    },
  },
  {
    name: "Design Thinking",
    description: "As 5 fases do processo de Design Thinking",
    category: "creative",
    node_count: 15,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Design Thinking", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -160 }, data: { label: "1. Empatia", color: "#C48BB4", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: -40 }, data: { label: "2. Definicao", color: "#EF4444", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: 280, y: 80 }, data: { label: "3. Ideacao", color: "#F59E0B", level: 1, side: "right" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: -120 }, data: { label: "4. Prototipagem", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: -280, y: 80 }, data: { label: "5. Teste", color: "#22C55E", level: 1, side: "left" } },
        { id: "n7", type: "mindmap", position: { x: 560, y: -200 }, data: { label: "Entrevistas", color: "#C48BB4", level: 2, side: "right" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -120 }, data: { label: "Observacao em Campo", color: "#C48BB4", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -40 }, data: { label: "Ponto de Vista (POV)", color: "#EF4444", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: 40 }, data: { label: "Brainstorming", color: "#F59E0B", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: 120 }, data: { label: "Crazy 8s", color: "#F59E0B", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "MVP", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: -80 }, data: { label: "Wireframes", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n14", type: "mindmap", position: { x: -560, y: 40 }, data: { label: "Teste com Usuarios", color: "#22C55E", level: 2, side: "left" } },
        { id: "n15", type: "mindmap", position: { x: -560, y: 120 }, data: { label: "Feedback e Iteracao", color: "#22C55E", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "right" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "left" },
        { id: "e2-7", source: "n2", target: "n7", type: "mindmap" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e3-9", source: "n3", target: "n9", type: "mindmap" },
        { id: "e4-10", source: "n4", target: "n10", type: "mindmap" },
        { id: "e4-11", source: "n4", target: "n11", type: "mindmap" },
        { id: "e5-12", source: "n5", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
        { id: "e6-14", source: "n6", target: "n14", type: "mindmap" },
        { id: "e6-15", source: "n6", target: "n15", type: "mindmap" },
      ],
    },
  },

  // ─── PRODUCTIVITY ───────────────────────────────────────────────────────────
  {
    name: "OKRs",
    description: "Objetivos e Resultados-Chave para planejamento estrategico",
    category: "productivity",
    node_count: 13,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "OKRs do Trimestre", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -160 }, data: { label: "Objetivo 1", color: "#22C55E", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: -280, y: -160 }, data: { label: "Objetivo 2", color: "#3B82F6", level: 1, side: "left" } },
        { id: "n4", type: "mindmap", position: { x: 280, y: 120 }, data: { label: "Objetivo 3", color: "#C48BB4", level: 1, side: "right" } },
        { id: "n5", type: "mindmap", position: { x: 560, y: -240 }, data: { label: "KR 1.1", color: "#22C55E", level: 2, side: "right" } },
        { id: "n6", type: "mindmap", position: { x: 560, y: -160 }, data: { label: "KR 1.2", color: "#22C55E", level: 2, side: "right" } },
        { id: "n7", type: "mindmap", position: { x: 560, y: -80 }, data: { label: "KR 1.3", color: "#22C55E", level: 2, side: "right" } },
        { id: "n8", type: "mindmap", position: { x: -560, y: -240 }, data: { label: "KR 2.1", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n9", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "KR 2.2", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n10", type: "mindmap", position: { x: -560, y: -80 }, data: { label: "KR 2.3", color: "#3B82F6", level: 2, side: "left" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: 40 }, data: { label: "KR 3.1", color: "#C48BB4", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: 560, y: 120 }, data: { label: "KR 3.2", color: "#C48BB4", level: 2, side: "right" } },
        { id: "n13", type: "mindmap", position: { x: 560, y: 200 }, data: { label: "KR 3.3", color: "#C48BB4", level: 2, side: "right" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "left" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "right" },
        { id: "e2-5", source: "n2", target: "n5", type: "mindmap" },
        { id: "e2-6", source: "n2", target: "n6", type: "mindmap" },
        { id: "e2-7", source: "n2", target: "n7", type: "mindmap" },
        { id: "e3-8", source: "n3", target: "n8", type: "mindmap" },
        { id: "e3-9", source: "n3", target: "n9", type: "mindmap" },
        { id: "e3-10", source: "n3", target: "n10", type: "mindmap" },
        { id: "e4-11", source: "n4", target: "n11", type: "mindmap" },
        { id: "e4-12", source: "n4", target: "n12", type: "mindmap" },
        { id: "e4-13", source: "n4", target: "n13", type: "mindmap" },
      ],
    },
  },
  {
    name: "Plano de Sprint",
    description: "Organizacao de sprint com backlog, tarefas e entregaveis",
    category: "productivity",
    node_count: 15,
    data: {
      nodes: [
        { id: "n1", type: "mindmap", position: { x: 0, y: 0 }, data: { label: "Sprint Planning", color: "#82B4C4", level: 0 } },
        { id: "n2", type: "mindmap", position: { x: 280, y: -160 }, data: { label: "Meta da Sprint", color: "#22C55E", level: 1, side: "right" } },
        { id: "n3", type: "mindmap", position: { x: 280, y: 0 }, data: { label: "Backlog Selecionado", color: "#C4A882", level: 1, side: "right" } },
        { id: "n4", type: "mindmap", position: { x: 280, y: 160 }, data: { label: "Entregaveis", color: "#3B82F6", level: 1, side: "right" } },
        { id: "n5", type: "mindmap", position: { x: -280, y: -160 }, data: { label: "Riscos e Impedimentos", color: "#EF4444", level: 1, side: "left" } },
        { id: "n6", type: "mindmap", position: { x: -280, y: 0 }, data: { label: "Capacidade do Time", color: "#8B9CC4", level: 1, side: "left" } },
        { id: "n7", type: "mindmap", position: { x: -280, y: 160 }, data: { label: "Cerimonias", color: "#7C9E8F", level: 1, side: "left" } },
        { id: "n8", type: "mindmap", position: { x: 560, y: -200 }, data: { label: "Objetivo de Negocio", color: "#22C55E", level: 2, side: "right" } },
        { id: "n9", type: "mindmap", position: { x: 560, y: -120 }, data: { label: "Criterio de Sucesso", color: "#22C55E", level: 2, side: "right" } },
        { id: "n10", type: "mindmap", position: { x: 560, y: -40 }, data: { label: "Historia 1", color: "#C4A882", level: 2, side: "right" } },
        { id: "n11", type: "mindmap", position: { x: 560, y: 40 }, data: { label: "Historia 2", color: "#C4A882", level: 2, side: "right" } },
        { id: "n12", type: "mindmap", position: { x: 560, y: 120 }, data: { label: "Historia 3", color: "#C4A882", level: 2, side: "right" } },
        { id: "n13", type: "mindmap", position: { x: -560, y: -160 }, data: { label: "Dependencias", color: "#EF4444", level: 2, side: "left" } },
        { id: "n14", type: "mindmap", position: { x: -560, y: -40 }, data: { label: "Velocidade", color: "#8B9CC4", level: 2, side: "left" } },
        { id: "n15", type: "mindmap", position: { x: -560, y: 120 }, data: { label: "Daily / Review / Retro", color: "#7C9E8F", level: 2, side: "left" } },
      ],
      edges: [
        { id: "e1-2", source: "n1", target: "n2", type: "mindmap", sourceHandle: "right" },
        { id: "e1-3", source: "n1", target: "n3", type: "mindmap", sourceHandle: "right" },
        { id: "e1-4", source: "n1", target: "n4", type: "mindmap", sourceHandle: "right" },
        { id: "e1-5", source: "n1", target: "n5", type: "mindmap", sourceHandle: "left" },
        { id: "e1-6", source: "n1", target: "n6", type: "mindmap", sourceHandle: "left" },
        { id: "e1-7", source: "n1", target: "n7", type: "mindmap", sourceHandle: "left" },
        { id: "e2-8", source: "n2", target: "n8", type: "mindmap" },
        { id: "e2-9", source: "n2", target: "n9", type: "mindmap" },
        { id: "e3-10", source: "n3", target: "n10", type: "mindmap" },
        { id: "e3-11", source: "n3", target: "n11", type: "mindmap" },
        { id: "e3-12", source: "n3", target: "n12", type: "mindmap" },
        { id: "e5-13", source: "n5", target: "n13", type: "mindmap" },
        { id: "e6-14", source: "n6", target: "n14", type: "mindmap" },
        { id: "e7-15", source: "n7", target: "n15", type: "mindmap" },
      ],
    },
  },
];

export async function POST() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !supabaseKey) {
    return NextResponse.json({ error: "Not configured" }, { status: 500 });
  }

  const supabase = createClient(supabaseUrl, supabaseKey);

  for (const template of STARTER_TEMPLATES) {
    await supabase.from("map_templates").upsert(
      { ...template, is_public: true },
      { onConflict: "name" }
    );
  }

  return NextResponse.json({ ok: true, count: STARTER_TEMPLATES.length });
}
