-- =============================================================================
-- Productization Migration for eximia-maps
-- Generated by @eximia/productization-hub from ProductContract v1.0.0
-- Contract: eximia-productization/v1
-- =============================================================================

-- User profiles table (stores plan & billing info, keyed by Gate user ID)
CREATE TABLE IF NOT EXISTS user_profiles (
  id uuid PRIMARY KEY,
  email text,
  name text,
  plan text DEFAULT 'free' CHECK (plan IN ('free', 'pro', 'business')),
  stripe_customer_id text UNIQUE,
  stripe_subscription_id text UNIQUE,
  subscription_status text DEFAULT 'inactive'
    CHECK (subscription_status IN ('active', 'canceled', 'past_due', 'trialing', 'incomplete', 'inactive')),
  current_period_end timestamptz,
  stripe_price_id text,
  role text DEFAULT 'user',
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- AI usage tracking table (monthly quotas)
CREATE TABLE IF NOT EXISTS ai_usage (
  user_id uuid REFERENCES user_profiles(id) ON DELETE CASCADE,
  month text NOT NULL,
  generation_count integer DEFAULT 0,
  PRIMARY KEY (user_id, month)
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_user_profiles_stripe_customer_id
  ON user_profiles(stripe_customer_id) WHERE stripe_customer_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ai_usage_user
  ON ai_usage(user_id);

-- RLS Policies
ALTER TABLE ai_usage ENABLE ROW LEVEL SECURITY;

CREATE POLICY "ai_usage_owner" ON ai_usage
  FOR ALL USING (user_id = auth.uid());

-- Ensure existing users get a profile row (run after migration)
-- INSERT INTO user_profiles (id) SELECT id FROM auth.users ON CONFLICT DO NOTHING;
